// Code generated by MockGen. DO NOT EDIT.
// Source: infra/contracts.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	opa "github.com/ditointernet/go-dito/opa"
	gomock "github.com/golang/mock/gomock"
)

// MockLogger is a mock of Logger interface.
type MockLogger struct {
	ctrl     *gomock.Controller
	recorder *MockLoggerMockRecorder
}

// MockLoggerMockRecorder is the mock recorder for MockLogger.
type MockLoggerMockRecorder struct {
	mock *MockLogger
}

// NewMockLogger creates a new mock instance.
func NewMockLogger(ctrl *gomock.Controller) *MockLogger {
	mock := &MockLogger{ctrl: ctrl}
	mock.recorder = &MockLoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogger) EXPECT() *MockLoggerMockRecorder {
	return m.recorder
}

// Critical mocks base method.
func (m *MockLogger) Critical(ctx context.Context, err error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Critical", ctx, err)
}

// Critical indicates an expected call of Critical.
func (mr *MockLoggerMockRecorder) Critical(ctx, err interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Critical", reflect.TypeOf((*MockLogger)(nil).Critical), ctx, err)
}

// Debug mocks base method.
func (m *MockLogger) Debug(ctx context.Context, msg string, args ...interface{}) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, msg}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Debug", varargs...)
}

// Debug indicates an expected call of Debug.
func (mr *MockLoggerMockRecorder) Debug(ctx, msg interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, msg}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Debug", reflect.TypeOf((*MockLogger)(nil).Debug), varargs...)
}

// Error mocks base method.
func (m *MockLogger) Error(ctx context.Context, err error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Error", ctx, err)
}

// Error indicates an expected call of Error.
func (mr *MockLoggerMockRecorder) Error(ctx, err interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*MockLogger)(nil).Error), ctx, err)
}

// Info mocks base method.
func (m *MockLogger) Info(ctx context.Context, msg string, args ...interface{}) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, msg}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Info", varargs...)
}

// Info indicates an expected call of Info.
func (mr *MockLoggerMockRecorder) Info(ctx, msg interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, msg}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Info", reflect.TypeOf((*MockLogger)(nil).Info), varargs...)
}

// Warning mocks base method.
func (m *MockLogger) Warning(ctx context.Context, msg string, args ...interface{}) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, msg}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Warning", varargs...)
}

// Warning indicates an expected call of Warning.
func (mr *MockLoggerMockRecorder) Warning(ctx, msg interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, msg}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Warning", reflect.TypeOf((*MockLogger)(nil).Warning), varargs...)
}

// MockJWKSClient is a mock of JWKSClient interface.
type MockJWKSClient struct {
	ctrl     *gomock.Controller
	recorder *MockJWKSClientMockRecorder
}

// MockJWKSClientMockRecorder is the mock recorder for MockJWKSClient.
type MockJWKSClientMockRecorder struct {
	mock *MockJWKSClient
}

// NewMockJWKSClient creates a new mock instance.
func NewMockJWKSClient(ctrl *gomock.Controller) *MockJWKSClient {
	mock := &MockJWKSClient{ctrl: ctrl}
	mock.recorder = &MockJWKSClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJWKSClient) EXPECT() *MockJWKSClientMockRecorder {
	return m.recorder
}

// Certs mocks base method.
func (m *MockJWKSClient) Certs() map[string]string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Certs")
	ret0, _ := ret[0].(map[string]string)
	return ret0
}

// Certs indicates an expected call of Certs.
func (mr *MockJWKSClientMockRecorder) Certs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Certs", reflect.TypeOf((*MockJWKSClient)(nil).Certs))
}

// GetCerts mocks base method.
func (m *MockJWKSClient) GetCerts(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCerts", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetCerts indicates an expected call of GetCerts.
func (mr *MockJWKSClientMockRecorder) GetCerts(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCerts", reflect.TypeOf((*MockJWKSClient)(nil).GetCerts), ctx)
}

// RenewCerts mocks base method.
func (m *MockJWKSClient) RenewCerts(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RenewCerts", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// RenewCerts indicates an expected call of RenewCerts.
func (mr *MockJWKSClientMockRecorder) RenewCerts(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenewCerts", reflect.TypeOf((*MockJWKSClient)(nil).RenewCerts), ctx)
}

// MockAuthorizatorClient is a mock of AuthorizatorClient interface.
type MockAuthorizatorClient struct {
	ctrl     *gomock.Controller
	recorder *MockAuthorizatorClientMockRecorder
}

// MockAuthorizatorClientMockRecorder is the mock recorder for MockAuthorizatorClient.
type MockAuthorizatorClientMockRecorder struct {
	mock *MockAuthorizatorClient
}

// NewMockAuthorizatorClient creates a new mock instance.
func NewMockAuthorizatorClient(ctrl *gomock.Controller) *MockAuthorizatorClient {
	mock := &MockAuthorizatorClient{ctrl: ctrl}
	mock.recorder = &MockAuthorizatorClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthorizatorClient) EXPECT() *MockAuthorizatorClientMockRecorder {
	return m.recorder
}

// DecideIfAllowed mocks base method.
func (m *MockAuthorizatorClient) DecideIfAllowed(ctx context.Context, regoQuery, method, path, brandID, userID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecideIfAllowed", ctx, regoQuery, method, path, brandID, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DecideIfAllowed indicates an expected call of DecideIfAllowed.
func (mr *MockAuthorizatorClientMockRecorder) DecideIfAllowed(ctx, regoQuery, method, path, brandID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecideIfAllowed", reflect.TypeOf((*MockAuthorizatorClient)(nil).DecideIfAllowed), ctx, regoQuery, method, path, brandID, userID)
}

// ExecuteQuery mocks base method.
func (m *MockAuthorizatorClient) ExecuteQuery(ctx context.Context, query string, input map[string]interface{}) (opa.AuthorizationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteQuery", ctx, query, input)
	ret0, _ := ret[0].(opa.AuthorizationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecuteQuery indicates an expected call of ExecuteQuery.
func (mr *MockAuthorizatorClientMockRecorder) ExecuteQuery(ctx, query, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteQuery", reflect.TypeOf((*MockAuthorizatorClient)(nil).ExecuteQuery), ctx, query, input)
}
