// Code generated by MockGen. DO NOT EDIT.
// Source: contracts.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	opa "github.com/ditointernet/go-dito/lib/opa"
	gomock "github.com/golang/mock/gomock"
)

// MockauthorizatorClient is a mock of authorizatorClient interface.
type MockauthorizatorClient struct {
	ctrl     *gomock.Controller
	recorder *MockauthorizatorClientMockRecorder
}

// MockauthorizatorClientMockRecorder is the mock recorder for MockauthorizatorClient.
type MockauthorizatorClientMockRecorder struct {
	mock *MockauthorizatorClient
}

// NewMockauthorizatorClient creates a new mock instance.
func NewMockauthorizatorClient(ctrl *gomock.Controller) *MockauthorizatorClient {
	mock := &MockauthorizatorClient{ctrl: ctrl}
	mock.recorder = &MockauthorizatorClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockauthorizatorClient) EXPECT() *MockauthorizatorClientMockRecorder {
	return m.recorder
}

// DecideIfAllowed mocks base method.
func (m *MockauthorizatorClient) DecideIfAllowed(ctx context.Context, regoQuery, method, path, brandID, userID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecideIfAllowed", ctx, regoQuery, method, path, brandID, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DecideIfAllowed indicates an expected call of DecideIfAllowed.
func (mr *MockauthorizatorClientMockRecorder) DecideIfAllowed(ctx, regoQuery, method, path, brandID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecideIfAllowed", reflect.TypeOf((*MockauthorizatorClient)(nil).DecideIfAllowed), ctx, regoQuery, method, path, brandID, userID)
}

// ExecuteQuery mocks base method.
func (m *MockauthorizatorClient) ExecuteQuery(ctx context.Context, query string, input map[string]interface{}) (opa.AuthorizationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteQuery", ctx, query, input)
	ret0, _ := ret[0].(opa.AuthorizationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecuteQuery indicates an expected call of ExecuteQuery.
func (mr *MockauthorizatorClientMockRecorder) ExecuteQuery(ctx, query, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteQuery", reflect.TypeOf((*MockauthorizatorClient)(nil).ExecuteQuery), ctx, query, input)
}

// Mocklogger is a mock of logger interface.
type Mocklogger struct {
	ctrl     *gomock.Controller
	recorder *MockloggerMockRecorder
}

// MockloggerMockRecorder is the mock recorder for Mocklogger.
type MockloggerMockRecorder struct {
	mock *Mocklogger
}

// NewMocklogger creates a new mock instance.
func NewMocklogger(ctrl *gomock.Controller) *Mocklogger {
	mock := &Mocklogger{ctrl: ctrl}
	mock.recorder = &MockloggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mocklogger) EXPECT() *MockloggerMockRecorder {
	return m.recorder
}

// Critical mocks base method.
func (m *Mocklogger) Critical(ctx context.Context, err error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Critical", ctx, err)
}

// Critical indicates an expected call of Critical.
func (mr *MockloggerMockRecorder) Critical(ctx, err interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Critical", reflect.TypeOf((*Mocklogger)(nil).Critical), ctx, err)
}

// Debug mocks base method.
func (m *Mocklogger) Debug(ctx context.Context, msg string, args ...interface{}) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, msg}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Debug", varargs...)
}

// Debug indicates an expected call of Debug.
func (mr *MockloggerMockRecorder) Debug(ctx, msg interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, msg}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Debug", reflect.TypeOf((*Mocklogger)(nil).Debug), varargs...)
}

// Error mocks base method.
func (m *Mocklogger) Error(ctx context.Context, err error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Error", ctx, err)
}

// Error indicates an expected call of Error.
func (mr *MockloggerMockRecorder) Error(ctx, err interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*Mocklogger)(nil).Error), ctx, err)
}

// Info mocks base method.
func (m *Mocklogger) Info(ctx context.Context, msg string, args ...interface{}) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, msg}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Info", varargs...)
}

// Info indicates an expected call of Info.
func (mr *MockloggerMockRecorder) Info(ctx, msg interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, msg}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Info", reflect.TypeOf((*Mocklogger)(nil).Info), varargs...)
}

// Warning mocks base method.
func (m *Mocklogger) Warning(ctx context.Context, msg string, args ...interface{}) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, msg}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Warning", varargs...)
}

// Warning indicates an expected call of Warning.
func (mr *MockloggerMockRecorder) Warning(ctx, msg interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, msg}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Warning", reflect.TypeOf((*Mocklogger)(nil).Warning), varargs...)
}
