name: Release Workflow

on:
  push:
    branches: [master, beta]

jobs:
  versioning:
    name: Define next release version
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18"
      - name: Install semantic release plugins
        run: npm ci
      - name: Define next release versions
        run: npm run release
        env:
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
