name: Release Workflow

on:
  push:
    branches: [main, beta]

permissions:
  contents: write
  issues: write
  pull-requests: write
  
jobs:
  versioning:
    name: Define next release version
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install semantic release plugins
        run: npm ci

      - name: Define next release versions
        run: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
